export const locations = {
  Alekseevka: "Alekseevka",
  Avdarma: "Avdarma",
  Baurchi: "Baurchi",
  Beshgioz: "Beshgioz",
  Beshalma: "Beshalma",
  Bujak: "Bujak",
  Cioc_Maidan: "Cioc-Maidan",
  Cismikoi: "Cismikoi",
  Dezginja: "Dezginja",
  Djoltai: "Djoltai",
  Dudulesht: "Dudulesht",
  Eutulia: "Eutulia",
  Eutulia_Noua: "Eutulia Nouă",
  Eutulia_station: "Eutulia, ж/д станция",
  Ferapontyevka: "Ferapontyevka",
  Gaydar: "Gaydar",
  Karbalia: "Karbalia",
  Kazaklia: "Kazaklia",
  Kirsova: "Kirsova",
  Kiriyet_Lunga: "Kiriyet-Lunga",
  Kongaz: "Kongaz",
  Kongazchik_de_Jos: "Nizhniy Kongazchik",
  Kongazchik_de_Sus: "Verkhniy Kongazchik",
  Kopchak: "Kopchak",
  Kotovskoe: "Kotovskoe",
  Russkaya_Kiseliya: "Russkaya Kiseliya",
  Svetliy: "Svetliy",
  Tomai: "Tomai",
  Taraclia: "Taraclia"
}

export const ru_translates = {
  [locations.Alekseevka]: "Алексеевка",
  [locations.Avdarma]: "Авдарма",
  [locations.Baurchi]: "Баурчи",
  [locations.Beshgioz]: "Бешгёз",
  [locations.Beshalma]: "Бешалма",
  [locations.Bujak]: "Буджак",
  [locations.Cioc_Maidan]: "Чок-Майдан",
  [locations.Cismikoi]: "Чишмикёй",
  [locations.Dezginja]: "Дезгинжа",
  [locations.Djoltai]: "Жолтай",
  [locations.Dudulesht]: "Дудулешть",
  [locations.Eutulia]: "Етулия",
  [locations.Eutulia_Noua]: "Етулия Ноуэ",
  [locations.Eutulia_station]: "Етулия, ж/д станция",
  [locations.Ferapontyevka]: "Ферапонтьевка",
  [locations.Gaydar]: "Гайдар",
  [locations.Karbalia]: "Карбалия",
  [locations.Kazaklia]: "Казаклия",
  [locations.Kirsova]: "Кирсова",
  [locations.Kiriyet_Lunga]: "Кириет-Лунга",
  [locations.Kongaz]: "Конгаз",
  [locations.Kongazchik_de_Jos]: "Конгазчикул де Жос",
  [locations.Kongazchik_de_Sus]: "Верхний Конгазчик",
  [locations.Kopchak]: "Копчак",
  [locations.Kotovskoe]: "Котовское",
  [locations.Russkaya_Kiseliya]: "Русская Киселия",
  [locations.Svetliy]: "Светлый",
  [locations.Tomai]: "Томай",
  [locations.Taraclia]: "Тараклия"
}

export const ro_translates = {
  [locations.Alekseevka]: "Alexeevca",
  [locations.Avdarma]: "Avdarma",
  [locations.Baurchi]: "Baurci",
  [locations.Beshgioz]: "Beșghioz",
  [locations.Beshalma]: "Beșalma",
  [locations.Bujak]: "Bugeac",
  [locations.Cioc_Maidan]: "Cioc-Maidan",
  [locations.Cismikoi]: "Cișmichioi",
  [locations.Dezginja]: "Dezghingea",
  [locations.Djoltai]: "Joltai",
  [locations.Dudulesht]: "Dudulești",
  [locations.Eutulia]: "Etulia",
  [locations.Eutulia_Noua]: "Etulia Nouă",
  [locations.Eutulia_station]: "Etulia, stație c.f.",
  [locations.Ferapontyevka]: "Ferapontievca",
  [locations.Gaydar]: "Gaidar",
  [locations.Karbalia]: "Carbalia",
  [locations.Kazaklia]: "Cazaclia",
  [locations.Kirsova]: "Chirsova",
  [locations.Kiriyet_Lunga]: "Chiriet-Lunga",
  [locations.Kongaz]: "Congaz",
  [locations.Kongazchik_de_Jos]: "Congazcicul de Jos",
  [locations.Kongazchik_de_Sus]: "Congazcicul de Sus",
  [locations.Kopchak]: "Copceac",
  [locations.Kotovskoe]: "Cotovscoe",
  [locations.Russkaya_Kiseliya]: "Chioselia Rusă",
  [locations.Svetliy]: "Svetlîi",
  [locations.Taraclia]: "Taraclia"
}




export const latlng_for_location = {
  [locations.Alekseevka]: { lat: 46.2422, lng: 28.7728 },
  [locations.Avdarma]: { lat: 46.2534, lng: 28.8391 },
  [locations.Baurchi]: { lat: 46.1833, lng: 28.7167 },
  [locations.Beshgioz]: { lat: 46.2000, lng: 28.6833 },
  [locations.Beshalma]: { lat: 46.1751, lng: 28.6503 },
  [locations.Bujak]: { lat: 46.3655, lng: 28.6625 },
  [locations.Cioc_Maidan]: { lat: 46.1667, lng: 28.6167 },
  [locations.Cismikoi]: { lat: 45.5470, lng: 28.3817 },
  [locations.Dezginja]: { lat: 46.4244, lng: 28.6167 },
  [locations.Djoltai]: { lat: 46.2167, lng: 28.7167 },
  [locations.Dudulesht]: { lat: 46.2500, lng: 28.7000 },
  [locations.Eutulia]: { lat: 45.5375, lng: 28.4405 },
  [locations.Eutulia_Noua]: { lat: 45.5153, lng: 28.4374 },
  [locations.Eutulia_station]: { lat: 45.5300, lng: 28.4450 },
  [locations.Ferapontyevka]: { lat: 46.2667, lng: 28.7000 },
  [locations.Gaydar]: { lat: 46.2000, lng: 28.8000 },
  [locations.Karbalia]: { lat: 45.8715, lng: 28.4493 },
  [locations.Kazaklia]: { lat: 46.0108, lng: 28.6628 },
  [locations.Kirsova]: { lat: 46.2833, lng: 28.6667 },
  [locations.Kiriyet_Lunga]: { lat: 46.1500, lng: 28.8000 },
  [locations.Kongaz]: { lat: 46.2333, lng: 28.6333 },
  [locations.Kongazchik_de_Jos]: { lat: 46.2167, lng: 28.6167 },
  [locations.Kongazchik_de_Sus]: { lat: 46.2500, lng: 28.6500 },
  [locations.Kopchak]: { lat: 46.1833, lng: 28.7500 },
  [locations.Kotovskoe]: { lat: 46.2667, lng: 28.6833 },
  [locations.Russkaya_Kiseliya]: { lat: 46.3000, lng: 28.7000 },
  [locations.Svetliy]: { lat: 46.2667, lng: 28.6667 },
  [locations.Tomai]: { lat: 46.2000, lng: 28.7000 },
  [locations.Taraclia]: { lat: 45.90097758659668, lng: 28.661995259788767 }
};

