worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 768;
}
http {
    server {
        server_name main_server;
        charset utf-8;
        autoindex on;
        root /var/www/qrmenu/;
        include    conf.d/mime.types;
        # Static content
        listen 80;

        location / {
        	proxy_pass http://frontend;

		#	location /_next {
		#		alias /app/.next/;
		#		expires 30d;
		#		access_log on;
		#	}

			location /api {
				proxy_pass http://qrcodesapi;

			}
			location /api-static {
				proxy_pass http://qrcodesapi/static/;
			}

        }
    }
    client_max_body_size 20M;
}
