worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 768;
}
http {

log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '$http_host $upstream_response_time $request_time '
    'azzzza: $http_upgrade ==s';

	map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    server {
        server_name main_server;
        charset utf-8;
        autoindex on;
        root /var/www/qrmenu/;
        include    conf.d/mime.types;
        # Static content
        listen 80;

        location / {
        	proxy_pass http://frontend;
        	
          location /admin {
            try_files $uri /admin/index.html;
          }
          location /courier {
            try_files $uri /admin/index.html;
          }
          location /static {
            alias /var/www/qrmenu/admin/static;
            try_files $uri $uri/ =404;
          }

          location /ws {
            proxy_pass http://qrcodesapi;
            proxy_http_version 1.1;
            proxy_connect_timeout 4s;
            proxy_read_timeout 120s;
            proxy_send_timeout 12s;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

          }
          location /api {
            proxy_pass http://qrcodesapi;

          }
          location /api-static {
            alias /var/www/qrmenuapi/clientfiles/;
            try_files $uri $uri/ =404;
          }
          location /.well-known {
            alias /var/www/qrmenu/.well-known/;
            try_files $uri $uri/ =404;
          }
        }
    }
    client_max_body_size 20M;
}
